# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - student-grades

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '8'

    - name: Build with Maven
      env: # Or as an environment variable
        AZ_DATABASE_NAME: ${{ secrets.AZ_DATABASE_NAME }}
        AZ_MYSQL_PASSWORD: ${{ secrets.AZ_MYSQL_PASSWORD }}
      run: mvn clean install

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'student-grades'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c1417e94e7a24dfa983ccca165fafd9c }}
        package: '${{ github.workspace }}/target/*.jar'